name: API CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  
jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
      - uses: actions/checkout@v4 # git clone into runner

      - name: Setup Nodejs
      - uses: actions/setup-node@v4
        with:
          node-version: 20.x
          
      - name: Install Dependecies
      - run: npm install

      - name: Run unit and integration tests
      - run: npm run tes

      - name: Run code linter
      - run: npm run lint

